Update links for docs, GitHub and license
cookieninja-generator/cookieninja pull request #58
Opened 2023-01-17 13:24 UTC by Havegum

These four likely should refer to `cookieninja`, not `cookiecutter`. Closes #57

2023-01-17 22:51 UTC, yuvaldolev requested changes
Hi, thanks for your contribution!
We started using conventional commits as a style guide for the project's commit messages: https://www.conventionalcommits.org/en/v1.0.0

We'd love it if you could update your commit message to follow this style guide.
We'll integrate a proper linter for the commit messages in the next version.

2023-01-21 12:12 UTC, Havegum commented
I've force-pushed an amend to the commit message to start with `docs:`. I wasn't sure if there exists a more appropriate tag to distinguish readme-changes from other documentation. Let me know if that's the case

2023-01-22 21:47 UTC, yuvaldolev approved these changes
@Havegum Nice!

2023-01-22 22:57 UTC, yuvaldolev commented
/rebase

2023-01-22 23:02 UTC, merged